sudo: required
language: node_js
services:
  - docker

before_install:
  - docker build -t day34/docker-react-sample -f Dockerfile.dev .

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-sample"
  env: "DockerReactSample-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-878392923027"
  bucket_path: "docker-react-sample"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"